// ptouchevent.h
// The touch pad event.
//
// Copyright 2012 - 2014 by Future Interface. 
// This software is licensed under the terms of the MIT license.
//
// Xujihao xujihao@gmail.com
//
// 


P_EVENTPARAMETER__TOUCH_CURSOR_ID     = 0,  // puint32
P_EVENTPARAMETER__TOUCH_X                ,  // pint32
P_EVENTPARAMETER__TOUCH_Y                ,  // pint32
P_EVENTPARAMETER__TOUCH_TIMESTAMP        ,  // puint32

P_EVENTPARAMETER__TOUCH_PARAMETER_FIRST = P_EVENTPARAMETER__TOUCH_CURSOR_ID,
P_EVENTPARAMETER__TOUCH_PARAMETER_LAST = P_EVENTPARAMETER__TOUCH_TIMESTAMP,

P_EVENTPARAMETER__TOUCH_PARAMETER_NUMBER = P_EVENTPARAMETER__TOUCH_PARAMETER_LAST - P_EVENTPARAMETER__TOUCH_PARAMETER_FIRST + 1,
